version: 2

before:
  hooks:
    - go mod tidy
    - sh -c "cd web && npm ci && npm run build"

builds:
  - id: nats-insight
    main: ./cmd/nats-insight/
    binary: nats-insight
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^memos:'
      - '^test:'
      - '^ci:'

release:
  github:
    owner: seralaci
    name: nats-insight
